<?php

/**
 * hook_preprocess_html()
 */

function lulzbot_preprocess_html(&$vars) {

  // $theme_path = drupal_get_path('theme', 'lulzbot');

  // drupal_add_js($theme_path . '/build/img/svg/grunticon.loader.js');
  // drupal_add_js('grunticon(["' . $theme_path . '/build/img/grunticon/icons.data.svg.css", "' . $theme_path . '/build/img/grunticon/icons.data.png.css", "' . $theme_path . '/build/img/grunticon/icons.fallback.css"], grunticon.svgLoadedCallback);', 'inline');
}
