<?php

/**
 * Implements hook_views_api().
 */
function lulzbot_home_views_api() {
  return array('api' => 3.0);
}

/**
 * Implements hook_views_default_views().
 */
function lulzbot_home_views_default_views() {
  return stools_views_from_directory_scan('lulzbot_home');
}

/**
 * Implements hook_menu().
 */
function lulzbot_home_menu() {
  $items = array();
  $items['home'] = array(
    'title' => 'Home',
    'page callback' => 'lulzbot_home_empty',
    'access callback' => true,
    'type' => MENU_CALLBACK,
  );
  return $items;
}

/**
 * Returns empty page.
 */
function lulzbot_home_empty() {
  return '';
}
